---
version: "3"

env:
  BIN_DIR:
    # BIN_DIR is the directory to hold the binaries. If run as root/administrator, the system directory is used.
    # Otherwise, the user's bin directory is used.
    # Task treats environmental variables as case-sensitive while Windows does not.
    sh: |
      {{- if eq OS "windows" -}}
          if net session >/dev/null 2>&1; then
              echo '{{.ProgramData}}\taskfiles\bin'
          else
              echo '{{.USERPROFILE}}\bin'
          fi
      {{- else -}}
          echo '{{ if eq .USER "root"}}/usr/local/bin{{ else }}{{.HOME}}/bin{{ end }}'
      {{- end -}}

# Include all the tasks at the top level, so they can include tasks in other files. If the tasks are included in the
# sub-files, the tasks are repeated in the 'task --list' output. Including all tasks at the top level prevents this
# duplication.
includes:
  init:
    taskfile: init/Init-Tasks.yaml
    optional: true
  install:
    taskfile: install/Install-Tasks.yaml
    optional: true
  github:
    taskfile: github/GitHub-Tasks.yaml
    optional: true

tasks:
  donothing: 'true'
