---
version: "3"

env:
  BIN_DIR:
    # BIN_DIR is the directory to hold the binaries. If run as root/administrator, the system directory is used.
    # Otherwise, the user's bin directory is used.
    # Task treats environmental variables as case-sensitive while Windows does not.
    sh: |
      {{- if eq OS "windows" -}}
          if net session >/dev/null 2>&1; then
              echo '{{.ProgramData}}\taskfiles\bin'
          else
              echo '{{.USERPROFILE}}\bin'
          fi
      {{- else -}}
          echo '{{if eq .USER "root"}}/usr/local/bin{{else}}{{.HOME}}/bin{{end}}'
      {{- end -}}

includes:
  init: Initialize-Tasks.yaml
  github: GitHub-Tasks.yaml
  download: Download-Tasks.yaml
