---
name: Create release

on:
  push:
    branches-ignore:
      - 'develop'
    tags:
      - 'v*'

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          archive_format="zip"
          git archive \
            --format ${archive_format} \
            --output /tmp/taskfiles-${GITHUB_REF_NAME}.${archive_format} \
            --prefix taskfiles-${GITHUB_REF_NAME}/ \
            --worktree-attributes \
            "${GITHUB_REF_NAME}"

          archive_format="tar.gz"
          git archive \
            --format ${archive_format} \
            --output /tmp/taskfiles-${GITHUB_REF_NAME}.${archive_format} \
            --prefix taskfiles-${GITHUB_REF_NAME}/ \
            --worktree-attributes \
            "${GITHUB_REF_NAME}"

          gh release create "${GITHUB_REF_NAME}" \
              --repo="${GITHUB_REPOSITORY}" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
              /tmp/taskfiles-${GITHUB_REF_NAME}.*

      - name: Use context variables
        run: |
          echo "$EVENT_CONTEXT"
        env:
          EVENT_CONTEXT: ${{ toJson(github.event) }}
